'use strict';

const STATUS_WAITING = 'waiting';
const STATUS_WORKING = 'working';
const STATUS_FINISHED = 'finished';
const STATUS_DISCARDED = 'discarded';

const STATUS_LIST = [STATUS_WAITING, STATUS_WORKING, STATUS_FINISHED, STATUS_DISCARDED];

module.exports = {
    STATUS_LIST,
    STATUS_WAITING,
    STATUS_WORKING,
    STATUS_FINISHED,
    STATUS_DISCARDED
};
